### ISSUE TITLE
How to have program ignore faceless frames without excluding them or throwing an error?

### ISSUE THREAD

**Issue by MalachiMassey** [Rudrabha/Wav2Lip#190]
The title is pretty explanatory. I just want to export videos where the frames with faces have the lip movement changed, but the faceless frames are ignored, but still included as normal in the final product. This can be helpful in the case of fixing dubbed videos where the speaker/actor briefly leaves the frame.

**Comment by prajwalkr** [comment]
You need to exclude that frame from being passed to Wav2Lip, and generate results for the rest of the frames. For the missing frames, simply use the original video frame without any changes.

**Comment by MalachiMassey** [comment]
That seems rather labor-intensive in the case that an actor keeps ducking out of a frame or something similar. Is there are way to have these frames ignored by editing the code or run parameters?

**Comment by Rudrabha** [comment]
You can change things inside this [if statement ](https://github.com/Rudrabha/Wav2Lip/blob/67eacb185d34b8843c3d4309c6d2d0379342065c/inference.py#L90). Instead of throwing this error, you can appropriately handle it. For example you can store the frame (or even the frame number) in a separate dictionary. You can further give some dummy (x1, y1), (x2, y2) in these cases.. While generating the final video, you need to use the original frame for all the frame numbers present in the undetected array. Hope this gives you an idea on what to do. Please also submit a pull request if you are able to handle such cases. We will like to add it as an option in our code.

**Comment by MalachiMassey** [comment]
Thank you. I will look into it and see what I can come up with.

**Comment by prajwalkr** [comment]
Please re-open again if required

**Comment by dheerajmpai** [comment]
A small trick we had used was to just run wav2lip on the first pixel when there is no face. This works fine with us.

**Comment by MalachiMassey** [comment]
What do you replace the error throwing code with in that case, @dheerajmpai? I suppose this is more of a work-around than a viable feature, but I'd like to at least give it a try.

**Comment by SaadBazaz** [comment]
@dheerajmpai Where did you use this code? Would need this too.

**Comment by SaadBazaz** [comment]
A switch like ```--use-original-where-faceless-frames``` or something would be great.
