### ISSUE TITLE
Init syncnet_wt 0.0

### ISSUE THREAD

**Issue by sunshower76** [Rudrabha/Wav2Lip#272]
Hi.
Thanks for your great work.

and, I have a question.

You wrote the reason that the initial value of syncnet_wt = 0 is the purpose of fast convergence.

Does this mean that we can get equal results with the initial syncnet_wt=0.03?

Finally, could I know a convergence value of sync loss?

Thank you!

**Comment by Rudrabha** [comment]
We train the network to predict decently correct lip-shapes before starting to penalize the quality of lip-shapes using the sync loss. So, we keep the weight to the sync loss as 0 in the beginning before using 0.03 as the training progresses.

**Comment by sunshower76** [comment]
@Rudrabha Thank you for you replying.
and, Can I give you one more question?
Why did you set the adv_wt=0.03 and did not any weight to discriminator loss?
Would it make the discriminator get more powerful than generator?

**Comment by Rudrabha** [comment]
The generator is already trained by the time we introduce the discriminator. So we try to achieve two things by doing this - 
1. The generator does not lose its knowledge about sync, which is paramount to the work. We only want to improve the visual quality and sharpness of the image.
2. Since the Gen is already trained and the disc starts from scratch, it ensures that the disc learns faster than the generator. 

I hope these explanations help.
