### ISSUE TITLE
Generated result trembles

### ISSUE THREAD

**Issue by godzilla-123** [Rudrabha/Wav2Lip#278]
I tried training wav2lip model on a personal dataset. The generated result looks fine when the audio only contains speech but it trembles when the audio contains both silence and speech. I guess it's because the model can't model silence correctly (the generated video doesn't have much linkage with the audio). Has anyone faced similiar problems?

https://user-images.githubusercontent.com/84270087/120583939-abe95700-c461-11eb-9fa7-06c48747b056.mp4

**Comment by Rudrabha** [comment]
Hi,
Congratulations on training Wav2Lip successfully on your own dataset. Silences are a challenge for such models. Originally Wav2Lip actually does decently well on silences. But there will be some cases where it will fail. Since you have trained the model on presumably smaller amounts of data that might have had no silent regions, the model might have a hard time dealing with them. You may try to augment your data with some silent parts for some performance improvement. In the long run, dealing with silences is a research direction.

**Comment by godzilla-123** [comment]
Thanks for your reply! The dataset I trained on contains only one speaker and it actually contains more videos for this speaker 
than any individual speaker in LRS2. I've also included silence during training, but the result still trembles...

We're trying to solve this problem by adding temporal dependency using LSTM. Is there any suggestion you can give us?

**Comment by BertyWooster** [comment]
@godzilla-123, can you please mention the amount of your training data?
