### ISSUE TITLE
Can we use lrs3 dataset

### ISSUE THREAD

**Issue by qustions** [Rudrabha/Wav2Lip#49]
Hi, @prajwalkr 
can we use the lrs3 dataset if yes what's the preprocessing?
and how does fps matters

**Comment by prajwalkr** [comment]
Yes, you can try with LRS3 without many changes to the code. The FPS of LRS3 videos is 25, so it won't be much of an issue.

**Comment by qustions** [comment]
How does fps effect training what will happen if fps of the video is 30

**Comment by prajwalkr** [comment]
Then the mel_step_size changes for 5 frames, i.e. the audio window changes. Consequently, you need to tweak the architectures a bit.

**Comment by Rudrabha** [comment]
Even though training on LRS3 is possible with the current code, it may not lead to any significant improvement. The resolution in LRS3 is similar to that of LRS2. LRS3 has more identities, so that can be a plus. However, the most significant disadvantage of LRS3 is that all the videos are recorded in indoor settings with typically a dark background. This leads to a lot of artifacts in the face boundary.
