### ISSUE TITLE
When there is no face in some frames in video, how to handle that situation.

### ISSUE THREAD

**Issue by nishantparihar** [Rudrabha/Wav2Lip#532]
In some frames in a video there is no face available. Due to this no face error I am getting. I want to have those frames in my video while keeping the audio playing. How can I do this??

**Comment by nishantparihar** [comment]
then how can I lip sync a video where some frames don't have faces.

**Comment by PrabalS12** [comment]
Did you find a solution to this?

**Comment by Akash-Jariwala** [comment]
> Did you find a solution to this?

Not yet.

**Comment by Harry5396** [comment]
you should skip the frame without face and still increase the index of the frame.
we should do this at processes:
- prepare frames for training
- prepare frames for inference: skip inference if there is no face in that frame.

**Comment by PrabalS12** [comment]
well the video I'm trying to lipsync is slightly over a minute long, hence I have to anyway trim it into shorter clips, however are you saying that i must concurrently run a face detection that if detects Yes, continue inference else, skip the part, and resume inference as soon as it detects face again?

**Comment by Harry5396** [comment]
In your case, you want to use inference and in your video there are some frames without faces which will result in line 79 error in inference.py.

So I recommend updating the inference.py file:

def face_detect()
- If the frame does not have a face, you should add value to results like this "[img], [ ]". Where "img" is the original frame, the empty list represents that frame without a face.

def datagen()
- you will check if the coords variable in line 124 is empty list, you should add a random matrix with shape of "96x96x3" to add to img_batch, and coords_batch will add an empty list.

then in the main() function:

line 267: for loop
you will check if `len(coords)` is 0 you will write the frame to the output video, otherwise do as the code shown.

Hope this guide helps!

**Comment by PrabalS12** [comment]
while inference training completes 100%, after making the recommended changes, however, it gives a ValueError in the main() function line 266 of my modified inference.py file. [too many values to unpack, (expected 4, got 0)] looks something related to coords.

The modified inference.py file is here for your reference:-

https://drive.google.com/file/d/1BtCW3b0jbj51MFBSKrNpRTeRjIS8qUnl/view?usp=sharing

**Comment by PrabalS12** [comment]
yeah terrible negligence, it works, thanks a lot man @Harry5396

**Comment by nishantparihar** [comment]
> 

@PrabalS12 please share final changed file here.

**Comment by lucydjo** [comment]
> yeah terrible negligence, it works, thanks a lot man @Harry5396

Can you share the code? Thanks!

**Comment by lucydjo** [comment]
> > 
> 
> @PrabalS12 please share final changed file here.

I have make gist with working inference  : https://gist.github.com/lucydjo/8119fe1f87bc69d0319ad81034ea3fc2
